# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_GUI_windows.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QSplitter, QTabWidget,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        font = QFont()
        font.setFamilies([u"DB Adman X"])
        font.setPointSize(13)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 5, 1281, 721))
        font1 = QFont()
        font1.setPointSize(14)
        self.tabWidget.setFont(font1)
        self.main = QWidget()
        self.main.setObjectName(u"main")
        self.groupBox = QGroupBox(self.main)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(15, 325, 391, 201))
        font2 = QFont()
        font2.setBold(True)
        self.groupBox.setFont(font2)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 65, 31, 21))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(5, 115, 111, 21))
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 140, 81, 26))
        self.lbl_customer_name = QLabel(self.groupBox)
        self.lbl_customer_name.setObjectName(u"lbl_customer_name")
        self.lbl_customer_name.setGeometry(QRect(55, 65, 341, 21))
        font3 = QFont()
        font3.setFamilies([u"DB Adman X"])
        font3.setPointSize(16)
        font3.setBold(True)
        self.lbl_customer_name.setFont(font3)
        self.lbl_customer_name.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_customer_Group = QLabel(self.groupBox)
        self.lbl_customer_Group.setObjectName(u"lbl_customer_Group")
        self.lbl_customer_Group.setGeometry(QRect(120, 114, 256, 26))
        self.lbl_customer_Group.setFont(font3)
        self.lbl_customer_Group.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_customer_LeadGroupName = QLabel(self.groupBox)
        self.lbl_customer_LeadGroupName.setObjectName(u"lbl_customer_LeadGroupName")
        self.lbl_customer_LeadGroupName.setGeometry(QRect(95, 140, 276, 26))
        self.lbl_customer_LeadGroupName.setFont(font3)
        self.lbl_customer_LeadGroupName.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 40, 31, 21))
        self.lbl_customer_ID = QLabel(self.groupBox)
        self.lbl_customer_ID.setObjectName(u"lbl_customer_ID")
        self.lbl_customer_ID.setGeometry(QRect(60, 35, 96, 26))
        self.lbl_customer_ID.setFont(font3)
        self.lbl_customer_ID.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_customer_Address = QLabel(self.groupBox)
        self.lbl_customer_Address.setObjectName(u"lbl_customer_Address")
        self.lbl_customer_Address.setGeometry(QRect(70, 85, 236, 26))
        self.lbl_customer_Address.setFont(font3)
        self.lbl_customer_Address.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(15, 90, 51, 16))
        self.label_31 = QLabel(self.groupBox)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 170, 106, 21))
        self.lbl_customer_phone = QLabel(self.groupBox)
        self.lbl_customer_phone.setObjectName(u"lbl_customer_phone")
        self.lbl_customer_phone.setGeometry(QRect(100, 170, 266, 26))
        self.lbl_customer_phone.setFont(font3)
        self.lbl_customer_phone.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.btn_customerSelect = QPushButton(self.groupBox)
        self.btn_customerSelect.setObjectName(u"btn_customerSelect")
        self.btn_customerSelect.setGeometry(QRect(315, 25, 61, 32))
        self.txt_customerID = QLineEdit(self.groupBox)
        self.txt_customerID.setObjectName(u"txt_customerID")
        self.txt_customerID.setGeometry(QRect(240, 30, 66, 26))
        self.label_18 = QLabel(self.groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(170, 30, 71, 26))
        self.groupBox_5 = QGroupBox(self.main)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(15, 90, 221, 141))
        self.groupBox_5.setFont(font2)
        self.label_29 = QLabel(self.groupBox_5)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 85, 31, 26))
        self.lbl_OrderID = QLabel(self.groupBox_5)
        self.lbl_OrderID.setObjectName(u"lbl_OrderID")
        self.lbl_OrderID.setGeometry(QRect(55, 65, 171, 16))
        self.lbl_OrderID.setFont(font3)
        self.lbl_OrderID.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_Order_Date = QLabel(self.groupBox_5)
        self.lbl_Order_Date.setObjectName(u"lbl_Order_Date")
        self.lbl_Order_Date.setGeometry(QRect(50, 90, 181, 16))
        self.lbl_Order_Date.setFont(font3)
        self.lbl_Order_Date.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.label_28 = QLabel(self.groupBox_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 55, 31, 36))
        self.label_30 = QLabel(self.groupBox_5)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 115, 31, 16))
        self.lbl_Order_Time = QLabel(self.groupBox_5)
        self.lbl_Order_Time.setObjectName(u"lbl_Order_Time")
        self.lbl_Order_Time.setGeometry(QRect(50, 115, 181, 16))
        self.lbl_Order_Time.setFont(font3)
        self.lbl_Order_Time.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.btn_orderSet = QPushButton(self.groupBox_5)
        self.btn_orderSet.setObjectName(u"btn_orderSet")
        self.btn_orderSet.setGeometry(QRect(150, 31, 61, 26))
        self.btn_orderSet.setStyleSheet(u"")
        self.txt_OrderID_Set = QLineEdit(self.groupBox_5)
        self.txt_OrderID_Set.setObjectName(u"txt_OrderID_Set")
        self.txt_OrderID_Set.setGeometry(QRect(10, 30, 131, 26))
        self.groupBox_6 = QGroupBox(self.main)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(15, 530, 226, 71))
        self.groupBox_6.setFont(font2)
        self.cmb_MaterialType = QComboBox(self.groupBox_6)
        self.cmb_MaterialType.setObjectName(u"cmb_MaterialType")
        self.cmb_MaterialType.setGeometry(QRect(10, 30, 171, 26))
        self.groupBox_8 = QGroupBox(self.main)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(415, 0, 856, 676))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(True)
        self.groupBox_8.setFont(font4)
        self.lbl_Clock = QLabel(self.groupBox_8)
        self.lbl_Clock.setObjectName(u"lbl_Clock")
        self.lbl_Clock.setGeometry(QRect(10, 30, 221, 66))
        font5 = QFont()
        font5.setFamilies([u"DB Adman X"])
        font5.setPointSize(70)
        font5.setBold(True)
        self.lbl_Clock.setFont(font5)
        self.lbl_Clock.setStyleSheet(u"color: rgb(0, 85, 127);")
        self.lbl_Clock.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.groupBox_8)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(15, 165, 151, 51))
        font6 = QFont()
        font6.setFamilies([u"DB Adman X"])
        font6.setPointSize(26)
        font6.setBold(True)
        font6.setItalic(False)
        self.label_14.setFont(font6)
        self.label_14.setStyleSheet(u"")
        self.groupBox_9 = QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(595, 20, 256, 311))
        self.groupBox_9.setFont(font2)
        self.groupBox_9.setStyleSheet(u"")
        self.btn_Grade_F = QPushButton(self.groupBox_9)
        self.btn_Grade_F.setObjectName(u"btn_Grade_F")
        self.btn_Grade_F.setGeometry(QRect(70, 130, 51, 32))
        font7 = QFont()
        font7.setFamilies([u"DB Adman X"])
        font7.setPointSize(18)
        font7.setBold(True)
        self.btn_Grade_F.setFont(font7)
        self.btn_Grade_F.setStyleSheet(u"background-color: rgb(252, 1, 7);")
        self.btn_Grade_B = QPushButton(self.groupBox_9)
        self.btn_Grade_B.setObjectName(u"btn_Grade_B")
        self.btn_Grade_B.setGeometry(QRect(70, 50, 51, 32))
        self.btn_Grade_B.setFont(font7)
        self.btn_Grade_B.setStyleSheet(u"background-color: rgb(128, 255, 7);")
        self.btn_Grade_C = QPushButton(self.groupBox_9)
        self.btn_Grade_C.setObjectName(u"btn_Grade_C")
        self.btn_Grade_C.setGeometry(QRect(10, 90, 51, 32))
        self.btn_Grade_C.setFont(font7)
        self.btn_Grade_C.setStyleSheet(u"background-color: rgb(255, 255, 10);")
        self.btn_Grade_D = QPushButton(self.groupBox_9)
        self.btn_Grade_D.setObjectName(u"btn_Grade_D")
        self.btn_Grade_D.setGeometry(QRect(70, 90, 51, 32))
        self.btn_Grade_D.setFont(font7)
        self.btn_Grade_D.setStyleSheet(u"background-color: rgb(253, 128, 8);")
        self.btn_Grade_A = QPushButton(self.groupBox_9)
        self.btn_Grade_A.setObjectName(u"btn_Grade_A")
        self.btn_Grade_A.setGeometry(QRect(10, 50, 51, 32))
        self.btn_Grade_A.setFont(font7)
        self.btn_Grade_A.setStyleSheet(u"background-color: rgb(16, 128, 64);")
        self.btn_Grade_E = QPushButton(self.groupBox_9)
        self.btn_Grade_E.setObjectName(u"btn_Grade_E")
        self.btn_Grade_E.setGeometry(QRect(10, 130, 51, 32))
        self.btn_Grade_E.setFont(font7)
        self.btn_Grade_E.setStyleSheet(u"background-color: rgb(252, 2, 128);")
        self.btn_Save_Main = QPushButton(self.groupBox_9)
        self.btn_Save_Main.setObjectName(u"btn_Save_Main")
        self.btn_Save_Main.setGeometry(QRect(155, 155, 91, 51))
        font8 = QFont()
        font8.setFamilies([u"DB Adman X"])
        font8.setPointSize(20)
        font8.setBold(True)
        self.btn_Save_Main.setFont(font8)
        self.btn_Save_Main.setStyleSheet(u"background-color: rgb(0, 170, 127);\n"
"")
        self.label_33 = QLabel(self.groupBox_9)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(155, 75, 91, 31))
        font9 = QFont()
        font9.setFamilies([u"DB Adman X"])
        font9.setPointSize(14)
        font9.setBold(True)
        font9.setItalic(False)
        self.label_33.setFont(font9)
        self.label_33.setStyleSheet(u"")
        self.label_33.setAlignment(Qt.AlignCenter)
        self.lbl_MaterialGrade_main = QLabel(self.groupBox_9)
        self.lbl_MaterialGrade_main.setObjectName(u"lbl_MaterialGrade_main")
        self.lbl_MaterialGrade_main.setGeometry(QRect(15, 185, 106, 116))
        font10 = QFont()
        font10.setFamilies([u"DB Adman X"])
        font10.setPointSize(120)
        font10.setBold(True)
        font10.setItalic(False)
        self.lbl_MaterialGrade_main.setFont(font10)
        self.lbl_MaterialGrade_main.setStyleSheet(u"color: rgb(0, 0, 127);\n"
"border-color: rgb(0, 85, 255);")
        self.lbl_MaterialGrade_main.setAlignment(Qt.AlignCenter)
        self.lbl_MaterialGrade_main.setMargin(5)
        self.btn_DeleteData_main = QPushButton(self.groupBox_9)
        self.btn_DeleteData_main.setObjectName(u"btn_DeleteData_main")
        self.btn_DeleteData_main.setGeometry(QRect(150, 270, 91, 32))
        self.btn_DeleteData_main.setStyleSheet(u"")
        self.txt_basketName = QLineEdit(self.groupBox_9)
        self.txt_basketName.setObjectName(u"txt_basketName")
        self.txt_basketName.setGeometry(QRect(155, 100, 91, 36))
        self.cmb_container = QComboBox(self.groupBox_9)
        self.cmb_container.setObjectName(u"cmb_container")
        self.cmb_container.setGeometry(QRect(155, 40, 86, 26))
        self.label_32 = QLabel(self.groupBox_9)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(160, 20, 71, 21))
        self.btn_ClearWeight = QPushButton(self.groupBox_9)
        self.btn_ClearWeight.setObjectName(u"btn_ClearWeight")
        self.btn_ClearWeight.setGeometry(QRect(150, 230, 91, 32))
        self.btn_ClearWeight.setStyleSheet(u"")
        self.lbl_dateNow = QLabel(self.groupBox_8)
        self.lbl_dateNow.setObjectName(u"lbl_dateNow")
        self.lbl_dateNow.setGeometry(QRect(10, 95, 221, 36))
        font11 = QFont()
        font11.setFamilies([u"DB Adman X"])
        font11.setPointSize(35)
        font11.setBold(True)
        self.lbl_dateNow.setFont(font11)
        self.lbl_dateNow.setStyleSheet(u"color: rgb(0, 85, 127);")
        self.lbl_dateNow.setAlignment(Qt.AlignCenter)
        self.lbl_weight = QLabel(self.groupBox_8)
        self.lbl_weight.setObjectName(u"lbl_weight")
        self.lbl_weight.setGeometry(QRect(65, 215, 476, 146))
        font12 = QFont()
        font12.setFamilies([u"DB Adman X"])
        font12.setPointSize(160)
        font12.setBold(True)
        font12.setItalic(False)
        self.lbl_weight.setFont(font12)
        self.lbl_weight.setStyleSheet(u"color: rgb(0, 170, 127)")
        self.lbl_weight.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.groupBox_8)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 355, 141, 31))
        font13 = QFont()
        font13.setPointSize(18)
        self.label_4.setFont(font13)
        self.tb_MainRecordDetail = QTableWidget(self.groupBox_8)
        self.tb_MainRecordDetail.setObjectName(u"tb_MainRecordDetail")
        self.tb_MainRecordDetail.setGeometry(QRect(10, 385, 836, 286))
        self.groupBox_22 = QGroupBox(self.groupBox_8)
        self.groupBox_22.setObjectName(u"groupBox_22")
        self.groupBox_22.setGeometry(QRect(250, 20, 341, 176))
        self.groupBox_22.setFont(font2)
        self.label_37 = QLabel(self.groupBox_22)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(15, 30, 31, 31))
        self.label_37.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lbl_customer_NameLeadGroup_main = QLabel(self.groupBox_22)
        self.lbl_customer_NameLeadGroup_main.setObjectName(u"lbl_customer_NameLeadGroup_main")
        self.lbl_customer_NameLeadGroup_main.setGeometry(QRect(100, 145, 236, 26))
        self.lbl_customer_NameLeadGroup_main.setFont(font3)
        self.lbl_customer_NameLeadGroup_main.setStyleSheet(u"color: rgb(16, 128, 64);")
        self.label = QLabel(self.groupBox_22)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(95, 60, 62, 36))
        self.lbl_Order_Date_main = QLabel(self.groupBox_22)
        self.lbl_Order_Date_main.setObjectName(u"lbl_Order_Date_main")
        self.lbl_Order_Date_main.setGeometry(QRect(225, 50, 111, 16))
        font14 = QFont()
        font14.setFamilies([u"DB Adman X"])
        font14.setPointSize(16)
        font14.setBold(True)
        font14.setItalic(False)
        self.lbl_Order_Date_main.setFont(font14)
        self.lbl_Order_Date_main.setStyleSheet(u"color: rgb(16, 128, 64);\n"
"")
        self.lbl_customer_name_main = QLabel(self.groupBox_22)
        self.lbl_customer_name_main.setObjectName(u"lbl_customer_name_main")
        self.lbl_customer_name_main.setGeometry(QRect(60, 120, 276, 26))
        self.lbl_customer_name_main.setFont(font14)
        self.lbl_customer_name_main.setStyleSheet(u"color: rgb(16, 128, 64);\n"
"")
        self.lbl_Order_Time_main = QLabel(self.groupBox_22)
        self.lbl_Order_Time_main.setObjectName(u"lbl_Order_Time_main")
        self.lbl_Order_Time_main.setGeometry(QRect(225, 25, 111, 21))
        self.lbl_Order_Time_main.setFont(font14)
        self.lbl_Order_Time_main.setStyleSheet(u"color: rgb(16, 128, 64);\n"
"")
        self.lbl_building_main = QLabel(self.groupBox_22)
        self.lbl_building_main.setObjectName(u"lbl_building_main")
        self.lbl_building_main.setGeometry(QRect(60, 65, 21, 26))
        self.lbl_building_main.setFont(font14)
        self.lbl_building_main.setStyleSheet(u"color: rgb(16, 128, 64);\n"
"")
        self.lbl_building_main.setAlignment(Qt.AlignCenter)
        self.lbl_OrderID_main = QLabel(self.groupBox_22)
        self.lbl_OrderID_main.setObjectName(u"lbl_OrderID_main")
        self.lbl_OrderID_main.setGeometry(QRect(55, 35, 111, 21))
        self.lbl_OrderID_main.setFont(font3)
        self.lbl_OrderID_main.setStyleSheet(u"color: rgb(16, 128, 64);")
        self.label_39 = QLabel(self.groupBox_22)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(15, 95, 62, 26))
        self.label_39.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_24 = QLabel(self.groupBox_22)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(15, 145, 76, 26))
        self.label_36 = QLabel(self.groupBox_22)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(180, 25, 36, 17))
        self.label_36.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_38 = QLabel(self.groupBox_22)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(15, 120, 36, 26))
        self.label_38.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_35 = QLabel(self.groupBox_22)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(188, 46, 31, 21))
        self.label_35.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lbl_Staff_name_main = QLabel(self.groupBox_22)
        self.lbl_Staff_name_main.setObjectName(u"lbl_Staff_name_main")
        self.lbl_Staff_name_main.setGeometry(QRect(75, 95, 261, 21))
        self.lbl_Staff_name_main.setFont(font14)
        self.lbl_Staff_name_main.setStyleSheet(u"color: rgb(16, 128, 64);\n"
"")
        self.label_40 = QLabel(self.groupBox_22)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(15, 70, 41, 16))
        self.label_40.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lbl_MaterialType_main = QLabel(self.groupBox_22)
        self.lbl_MaterialType_main.setObjectName(u"lbl_MaterialType_main")
        self.lbl_MaterialType_main.setGeometry(QRect(160, 65, 176, 26))
        self.lbl_MaterialType_main.setFont(font14)
        self.lbl_MaterialType_main.setStyleSheet(u"color: rgb(16, 128, 64);\n"
"")
        self.lbl_MaterialType_main.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.btn_RandomWeight = QPushButton(self.groupBox_8)
        self.btn_RandomWeight.setObjectName(u"btn_RandomWeight")
        self.btn_RandomWeight.setGeometry(QRect(750, 340, 91, 32))
        self.btn_RandomWeight.setStyleSheet(u"")
        self.btn_Create_Order = QPushButton(self.main)
        self.btn_Create_Order.setObjectName(u"btn_Create_Order")
        self.btn_Create_Order.setGeometry(QRect(75, 615, 266, 51))
        font15 = QFont()
        font15.setFamilies([u"DB Adman X"])
        font15.setPointSize(23)
        font15.setBold(True)
        self.btn_Create_Order.setFont(font15)
        self.btn_Create_Order.setStyleSheet(u"background-color: rgb(70, 212, 104);\n"
"")
        self.groupBox_7 = QGroupBox(self.main)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(250, 530, 111, 71))
        self.groupBox_7.setFont(font2)
        self.cmd_building = QComboBox(self.groupBox_7)
        self.cmd_building.setObjectName(u"cmd_building")
        self.cmd_building.setGeometry(QRect(10, 30, 86, 26))
        self.groupBox_11 = QGroupBox(self.main)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(255, 110, 151, 106))
        self.groupBox_11.setFont(font2)
        self.btn_SaveWasteWeight = QPushButton(self.groupBox_11)
        self.btn_SaveWasteWeight.setObjectName(u"btn_SaveWasteWeight")
        self.btn_SaveWasteWeight.setGeometry(QRect(15, 60, 126, 32))
        self.txt_wasteWeight = QLineEdit(self.groupBox_11)
        self.txt_wasteWeight.setObjectName(u"txt_wasteWeight")
        self.txt_wasteWeight.setGeometry(QRect(15, 25, 126, 31))
        self.txt_wasteWeight.setStyleSheet(u"")
        self.txt_wasteWeight.setAlignment(Qt.AlignCenter)
        self.groupBox_21 = QGroupBox(self.main)
        self.groupBox_21.setObjectName(u"groupBox_21")
        self.groupBox_21.setGeometry(QRect(255, 220, 151, 111))
        self.groupBox_21.setFont(font2)
        self.btn_SaveContainerWeight = QPushButton(self.groupBox_21)
        self.btn_SaveContainerWeight.setObjectName(u"btn_SaveContainerWeight")
        self.btn_SaveContainerWeight.setGeometry(QRect(15, 60, 121, 32))
        self.txt_ContainerWeight = QLineEdit(self.groupBox_21)
        self.txt_ContainerWeight.setObjectName(u"txt_ContainerWeight")
        self.txt_ContainerWeight.setGeometry(QRect(15, 25, 121, 31))
        self.txt_ContainerWeight.setStyleSheet(u"")
        self.txt_ContainerWeight.setAlignment(Qt.AlignCenter)
        self.groupBox_2 = QGroupBox(self.main)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(15, 235, 221, 91))
        self.groupBox_2.setFont(font2)
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 45, 31, 26))
        self.lbl_Staff_name = QLabel(self.groupBox_2)
        self.lbl_Staff_name.setObjectName(u"lbl_Staff_name")
        self.lbl_Staff_name.setGeometry(QRect(40, 50, 171, 21))
        font16 = QFont()
        font16.setFamilies([u"DB Adman X"])
        font16.setPointSize(15)
        font16.setBold(True)
        self.lbl_Staff_name.setFont(font16)
        self.lbl_Staff_name.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_Staff_name.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 25, 31, 21))
        self.lbl_Staff_ID = QLabel(self.groupBox_2)
        self.lbl_Staff_ID.setObjectName(u"lbl_Staff_ID")
        self.lbl_Staff_ID.setGeometry(QRect(50, 30, 176, 16))
        self.lbl_Staff_ID.setFont(font16)
        self.lbl_Staff_ID.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_Staff_ID.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lbl_UserLevelShow = QLabel(self.groupBox_2)
        self.lbl_UserLevelShow.setObjectName(u"lbl_UserLevelShow")
        self.lbl_UserLevelShow.setGeometry(QRect(40, 70, 101, 16))
        font17 = QFont()
        font17.setFamilies([u"DB Adman X"])
        font17.setPointSize(9)
        font17.setBold(False)
        font17.setItalic(False)
        self.lbl_UserLevelShow.setFont(font17)
        self.lbl_UserLevelShow.setStyleSheet(u"")
        self.lbl_UserLevelShow.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_50 = QLabel(self.main)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(10, 60, 441, 16))
        font18 = QFont()
        font18.setFamilies([u"DB Adman X"])
        font18.setPointSize(19)
        font18.setBold(True)
        font18.setItalic(False)
        font18.setStrikeOut(False)
        self.label_50.setFont(font18)
        self.label_50.setStyleSheet(u"color: rgb(240, 162, 101);\n"
"")
        self.label_50.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_51 = QLabel(self.main)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(5, 15, 441, 41))
        font19 = QFont()
        font19.setFamilies([u"DB Adman X"])
        font19.setPointSize(32)
        font19.setBold(True)
        self.label_51.setFont(font19)
        self.label_51.setStyleSheet(u"color: rgb(252, 62, 39);\n"
"")
        self.label_51.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.tabWidget.addTab(self.main, "")
        self.Resultes = QWidget()
        self.Resultes.setObjectName(u"Resultes")
        self.groupBox_10 = QGroupBox(self.Resultes)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(10, 0, 231, 141))
        self.groupBox_10.setFont(font2)
        self.label_5 = QLabel(self.groupBox_10)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 25, 81, 21))
        self.btn_CreateResulte = QPushButton(self.groupBox_10)
        self.btn_CreateResulte.setObjectName(u"btn_CreateResulte")
        self.btn_CreateResulte.setGeometry(QRect(30, 85, 171, 41))
        self.btn_CreateResulte.setFont(font3)
        self.btn_CreateResulte.setStyleSheet(u"background-color: rgb(70, 212, 104);")
        self.txt_OrderID_Search = QLineEdit(self.groupBox_10)
        self.txt_OrderID_Search.setObjectName(u"txt_OrderID_Search")
        self.txt_OrderID_Search.setGeometry(QRect(30, 50, 171, 26))
        self.groupBox_14 = QGroupBox(self.Resultes)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(5, 145, 236, 336))
        self.groupBox_14.setFont(font2)
        self.label_52 = QLabel(self.groupBox_14)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(15, 50, 28, 21))
        self.lbl_OrderID_3 = QLabel(self.groupBox_14)
        self.lbl_OrderID_3.setObjectName(u"lbl_OrderID_3")
        self.lbl_OrderID_3.setGeometry(QRect(55, 30, 141, 16))
        self.lbl_OrderID_3.setFont(font3)
        self.lbl_OrderID_3.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_Order_Date_3 = QLabel(self.groupBox_14)
        self.lbl_Order_Date_3.setObjectName(u"lbl_Order_Date_3")
        self.lbl_Order_Date_3.setGeometry(QRect(55, 50, 141, 21))
        self.lbl_Order_Date_3.setFont(font3)
        self.lbl_Order_Date_3.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.label_53 = QLabel(self.groupBox_14)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(10, 25, 36, 26))
        self.label_54 = QLabel(self.groupBox_14)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(15, 75, 28, 16))
        self.lbl_Order_Time_3 = QLabel(self.groupBox_14)
        self.lbl_Order_Time_3.setObjectName(u"lbl_Order_Time_3")
        self.lbl_Order_Time_3.setGeometry(QRect(55, 75, 141, 21))
        self.lbl_Order_Time_3.setFont(font3)
        self.lbl_Order_Time_3.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.label_6 = QLabel(self.groupBox_14)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(5, 100, 66, 31))
        self.label_6.setFont(font7)
        self.label_6.setStyleSheet(u"color:rgb(0, 170, 127)")
        self.label_55 = QLabel(self.groupBox_14)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(5, 180, 51, 26))
        self.label_55.setFont(font7)
        self.label_55.setStyleSheet(u"color:rgb(0, 170, 127)")
        self.lbl_Staff_name_3 = QLabel(self.groupBox_14)
        self.lbl_Staff_name_3.setObjectName(u"lbl_Staff_name_3")
        self.lbl_Staff_name_3.setGeometry(QRect(65, 150, 146, 21))
        self.lbl_Staff_name_3.setFont(font3)
        self.lbl_Staff_name_3.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_Staff_ID_2 = QLabel(self.groupBox_14)
        self.lbl_Staff_ID_2.setObjectName(u"lbl_Staff_ID_2")
        self.lbl_Staff_ID_2.setGeometry(QRect(65, 125, 146, 21))
        self.lbl_Staff_ID_2.setFont(font3)
        self.lbl_Staff_ID_2.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.label_45 = QLabel(self.groupBox_14)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 125, 41, 26))
        self.label_45.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_44 = QLabel(self.groupBox_14)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(20, 145, 23, 31))
        self.label_44.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_49 = QLabel(self.groupBox_14)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(10, 215, 26, 16))
        self.label_49.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_48 = QLabel(self.groupBox_14)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(5, 240, 76, 21))
        self.label_48.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lbl_customer_HeadGroup_2 = QLabel(self.groupBox_14)
        self.lbl_customer_HeadGroup_2.setObjectName(u"lbl_customer_HeadGroup_2")
        self.lbl_customer_HeadGroup_2.setGeometry(QRect(15, 260, 211, 21))
        self.lbl_customer_HeadGroup_2.setFont(font3)
        self.lbl_customer_HeadGroup_2.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_customer_ID_2 = QLabel(self.groupBox_14)
        self.lbl_customer_ID_2.setObjectName(u"lbl_customer_ID_2")
        self.lbl_customer_ID_2.setGeometry(QRect(60, 215, 141, 21))
        self.lbl_customer_ID_2.setFont(font3)
        self.lbl_customer_ID_2.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_building_2 = QLabel(self.groupBox_14)
        self.lbl_building_2.setObjectName(u"lbl_building_2")
        self.lbl_building_2.setGeometry(QRect(70, 280, 16, 21))
        self.lbl_building_2.setFont(font3)
        self.lbl_building_2.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_building_2.setAlignment(Qt.AlignCenter)
        self.label_59 = QLabel(self.groupBox_14)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(10, 280, 46, 21))
        self.label_59.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_58 = QLabel(self.groupBox_14)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(10, 305, 66, 21))
        self.lbl_MaterialType_2 = QLabel(self.groupBox_14)
        self.lbl_MaterialType_2.setObjectName(u"lbl_MaterialType_2")
        self.lbl_MaterialType_2.setGeometry(QRect(75, 305, 156, 21))
        self.lbl_MaterialType_2.setFont(font3)
        self.lbl_MaterialType_2.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.groupBox_16 = QGroupBox(self.Resultes)
        self.groupBox_16.setObjectName(u"groupBox_16")
        self.groupBox_16.setGeometry(QRect(535, 375, 376, 301))
        font20 = QFont()
        font20.setPointSize(16)
        font20.setBold(True)
        self.groupBox_16.setFont(font20)
        self.label_61 = QLabel(self.groupBox_16)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(10, 50, 101, 26))
        self.label_62 = QLabel(self.groupBox_16)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(10, 80, 211, 31))
        self.label_64 = QLabel(self.groupBox_16)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(10, 110, 216, 31))
        self.label_65 = QLabel(self.groupBox_16)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(15, 250, 176, 36))
        font21 = QFont()
        font21.setPointSize(20)
        self.label_65.setFont(font21)
        self.label_67 = QLabel(self.groupBox_16)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(280, 15, 91, 36))
        self.label_67.setAlignment(Qt.AlignCenter)
        self.label_68 = QLabel(self.groupBox_16)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(30, 135, 106, 26))
        self.label_68.setStyleSheet(u"")
        self.label_69 = QLabel(self.groupBox_16)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(30, 155, 106, 31))
        self.label_69.setStyleSheet(u"")
        self.label_70 = QLabel(self.groupBox_16)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(180, 135, 26, 26))
        self.label_70.setStyleSheet(u"")
        self.label_71 = QLabel(self.groupBox_16)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(180, 160, 51, 21))
        self.label_71.setStyleSheet(u"")
        self.lbl_Resulte_TotalBasket = QLabel(self.groupBox_16)
        self.lbl_Resulte_TotalBasket.setObjectName(u"lbl_Resulte_TotalBasket")
        self.lbl_Resulte_TotalBasket.setGeometry(QRect(140, 135, 26, 26))
        self.lbl_Resulte_TotalBasket.setStyleSheet(u"")
        self.lbl_Resulte_TotalBasket.setAlignment(Qt.AlignCenter)
        self.lbl_Resulte_weightBasket = QLabel(self.groupBox_16)
        self.lbl_Resulte_weightBasket.setObjectName(u"lbl_Resulte_weightBasket")
        self.lbl_Resulte_weightBasket.setGeometry(QRect(140, 160, 26, 21))
        self.lbl_Resulte_weightBasket.setStyleSheet(u"")
        self.lbl_Resulte_weightBasket.setAlignment(Qt.AlignCenter)
        self.lbl_Resulte_TotalWeightMeterial = QLabel(self.groupBox_16)
        self.lbl_Resulte_TotalWeightMeterial.setObjectName(u"lbl_Resulte_TotalWeightMeterial")
        self.lbl_Resulte_TotalWeightMeterial.setGeometry(QRect(275, 50, 96, 31))
        font22 = QFont()
        font22.setFamilies([u"DB Adman X"])
        font22.setPointSize(26)
        font22.setBold(True)
        self.lbl_Resulte_TotalWeightMeterial.setFont(font22)
        self.lbl_Resulte_TotalWeightMeterial.setStyleSheet(u"color:rgb(0, 0, 127)")
        self.lbl_Resulte_TotalWeightMeterial.setAlignment(Qt.AlignCenter)
        self.lbl_Resulte_TotalWeightReject = QLabel(self.groupBox_16)
        self.lbl_Resulte_TotalWeightReject.setObjectName(u"lbl_Resulte_TotalWeightReject")
        self.lbl_Resulte_TotalWeightReject.setGeometry(QRect(280, 90, 91, 16))
        self.lbl_Resulte_TotalWeightReject.setFont(font8)
        self.lbl_Resulte_TotalWeightReject.setStyleSheet(u"color:rgb(170, 0, 0)")
        self.lbl_Resulte_TotalWeightReject.setAlignment(Qt.AlignCenter)
        self.lbl_Resulte_TotalWeightBasket = QLabel(self.groupBox_16)
        self.lbl_Resulte_TotalWeightBasket.setObjectName(u"lbl_Resulte_TotalWeightBasket")
        self.lbl_Resulte_TotalWeightBasket.setGeometry(QRect(280, 120, 96, 16))
        self.lbl_Resulte_TotalWeightBasket.setFont(font8)
        self.lbl_Resulte_TotalWeightBasket.setStyleSheet(u"color:rgb(170, 0, 0)")
        self.lbl_Resulte_TotalWeightBasket.setAlignment(Qt.AlignCenter)
        self.lbl_Resulte_TotalWeight_toManuFactory = QLabel(self.groupBox_16)
        self.lbl_Resulte_TotalWeight_toManuFactory.setObjectName(u"lbl_Resulte_TotalWeight_toManuFactory")
        self.lbl_Resulte_TotalWeight_toManuFactory.setGeometry(QRect(210, 250, 146, 41))
        self.lbl_Resulte_TotalWeight_toManuFactory.setFont(font11)
        self.lbl_Resulte_TotalWeight_toManuFactory.setStyleSheet(u"color: rgb(0, 85, 0);")
        self.lbl_Resulte_TotalWeight_toManuFactory.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lbl_Resulte_ContainerWeight = QLabel(self.groupBox_16)
        self.lbl_Resulte_ContainerWeight.setObjectName(u"lbl_Resulte_ContainerWeight")
        self.lbl_Resulte_ContainerWeight.setGeometry(QRect(280, 190, 96, 21))
        self.lbl_Resulte_ContainerWeight.setFont(font8)
        self.lbl_Resulte_ContainerWeight.setStyleSheet(u"color:rgb(170, 0, 0)")
        self.lbl_Resulte_ContainerWeight.setAlignment(Qt.AlignCenter)
        self.label_104 = QLabel(self.groupBox_16)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setGeometry(QRect(10, 185, 186, 26))
        self.label_104.setStyleSheet(u"")
        self.label_102 = QLabel(self.groupBox_16)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setGeometry(QRect(10, 215, 236, 31))
        self.lbl_Resulte_TotalWeightReject_west = QLabel(self.groupBox_16)
        self.lbl_Resulte_TotalWeightReject_west.setObjectName(u"lbl_Resulte_TotalWeightReject_west")
        self.lbl_Resulte_TotalWeightReject_west.setGeometry(QRect(290, 220, 81, 21))
        self.lbl_Resulte_TotalWeightReject_west.setFont(font8)
        self.lbl_Resulte_TotalWeightReject_west.setStyleSheet(u"color:rgb(170, 0, 0)")
        self.lbl_Resulte_TotalWeightReject_west.setAlignment(Qt.AlignCenter)
        self.label_60 = QLabel(self.Resultes)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(260, 50, 236, 31))
        self.label_60.setFont(font13)
        self.groupBox_20 = QGroupBox(self.Resultes)
        self.groupBox_20.setObjectName(u"groupBox_20")
        self.groupBox_20.setGeometry(QRect(925, 375, 341, 236))
        font23 = QFont()
        font23.setPointSize(17)
        font23.setBold(True)
        self.groupBox_20.setFont(font23)
        self.label_91 = QLabel(self.groupBox_20)
        self.label_91.setObjectName(u"label_91")
        self.label_91.setGeometry(QRect(60, 80, 101, 20))
        self.label_91.setFont(font1)
        self.label_92 = QLabel(self.groupBox_20)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setGeometry(QRect(14, 55, 151, 26))
        self.label_93 = QLabel(self.groupBox_20)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setGeometry(QRect(260, 20, 71, 31))
        self.lbl_Resulte_TotalWeight_Accounting = QLabel(self.groupBox_20)
        self.lbl_Resulte_TotalWeight_Accounting.setObjectName(u"lbl_Resulte_TotalWeight_Accounting")
        self.lbl_Resulte_TotalWeight_Accounting.setGeometry(QRect(210, 60, 101, 21))
        self.lbl_Resulte_TotalWeight_Accounting.setFont(font22)
        self.lbl_Resulte_TotalWeight_Accounting.setStyleSheet(u"color:rgb(0, 0, 127)")
        self.lbl_Resulte_TotalWeight_Accounting.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_96 = QLabel(self.groupBox_20)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(10, 110, 176, 31))
        self.label_95 = QLabel(self.groupBox_20)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(10, 145, 66, 21))
        self.label_95.setFont(font1)
        self.label_95.setStyleSheet(u"")
        self.lbl_Resulte_Type = QLabel(self.groupBox_20)
        self.lbl_Resulte_Type.setObjectName(u"lbl_Resulte_Type")
        self.lbl_Resulte_Type.setGeometry(QRect(70, 145, 191, 21))
        font24 = QFont()
        font24.setFamilies([u"DB Adman X"])
        font24.setPointSize(14)
        self.lbl_Resulte_Type.setFont(font24)
        self.lbl_Resulte_Type.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_Resulte_Price = QLabel(self.groupBox_20)
        self.lbl_Resulte_Price.setObjectName(u"lbl_Resulte_Price")
        self.lbl_Resulte_Price.setGeometry(QRect(235, 115, 71, 26))
        font25 = QFont()
        font25.setPointSize(22)
        self.lbl_Resulte_Price.setFont(font25)
        self.lbl_Resulte_Price.setStyleSheet(u"")
        self.lbl_Resulte_Price.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_94 = QLabel(self.groupBox_20)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setGeometry(QRect(10, 185, 121, 21))
        self.lbl_Resulte_TotalPrice = QLabel(self.groupBox_20)
        self.lbl_Resulte_TotalPrice.setObjectName(u"lbl_Resulte_TotalPrice")
        self.lbl_Resulte_TotalPrice.setGeometry(QRect(135, 185, 181, 36))
        self.lbl_Resulte_TotalPrice.setFont(font11)
        self.lbl_Resulte_TotalPrice.setStyleSheet(u"color: rgb(0, 85, 0);")
        self.lbl_Resulte_TotalPrice.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_97 = QLabel(self.groupBox_20)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setGeometry(QRect(85, 205, 41, 20))
        self.label_97.setAlignment(Qt.AlignCenter)
        self.btn_UploadReport = QPushButton(self.Resultes)
        self.btn_UploadReport.setObjectName(u"btn_UploadReport")
        self.btn_UploadReport.setGeometry(QRect(1105, 625, 161, 46))
        self.btn_UploadReport.setFont(font3)
        self.btn_UploadReport.setStyleSheet(u"background-color: rgb(170, 255, 255);")
        self.tb_ReslutesDetail = QTableWidget(self.Resultes)
        self.tb_ReslutesDetail.setObjectName(u"tb_ReslutesDetail")
        self.tb_ReslutesDetail.setGeometry(QRect(255, 80, 1011, 291))
        self.label_56 = QLabel(self.Resultes)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(855, 5, 416, 41))
        font26 = QFont()
        font26.setFamilies([u"DB Adman X"])
        font26.setPointSize(34)
        font26.setBold(True)
        self.label_56.setFont(font26)
        self.label_56.setStyleSheet(u"color: rgb(252, 62, 39);\n"
"")
        self.label_56.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_57 = QLabel(self.Resultes)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(860, 50, 381, 16))
        font27 = QFont()
        font27.setFamilies([u"DB Adman X"])
        font27.setPointSize(20)
        font27.setBold(True)
        font27.setItalic(False)
        font27.setStrikeOut(False)
        self.label_57.setFont(font27)
        self.label_57.setStyleSheet(u"color: rgb(240, 162, 101);\n"
"")
        self.label_57.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.groupBox_17 = QGroupBox(self.Resultes)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(255, 375, 266, 301))
        self.groupBox_17.setFont(font2)
        self.lbl_Resulte_ExternalWeight = QLabel(self.groupBox_17)
        self.lbl_Resulte_ExternalWeight.setObjectName(u"lbl_Resulte_ExternalWeight")
        self.lbl_Resulte_ExternalWeight.setGeometry(QRect(25, 225, 176, 41))
        font28 = QFont()
        font28.setFamilies([u"DB Adman X"])
        font28.setPointSize(50)
        font28.setBold(True)
        self.lbl_Resulte_ExternalWeight.setFont(font28)
        self.lbl_Resulte_ExternalWeight.setStyleSheet(u"color:rgb(0, 0, 127)")
        self.lbl_Resulte_ExternalWeight.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_72 = QLabel(self.groupBox_17)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(15, 155, 131, 36))
        self.label_72.setFont(font21)
        self.label_72.setAlignment(Qt.AlignCenter)
        self.txt_ExternalWeightInput = QLineEdit(self.groupBox_17)
        self.txt_ExternalWeightInput.setObjectName(u"txt_ExternalWeightInput")
        self.txt_ExternalWeightInput.setGeometry(QRect(120, 50, 126, 41))
        self.btn_SaveExternalWeight = QPushButton(self.groupBox_17)
        self.btn_SaveExternalWeight.setObjectName(u"btn_SaveExternalWeight")
        self.btn_SaveExternalWeight.setGeometry(QRect(120, 100, 126, 31))
        self.checkBox_ExteranalWeight = QCheckBox(self.groupBox_17)
        self.checkBox_ExteranalWeight.setObjectName(u"checkBox_ExteranalWeight")
        self.checkBox_ExteranalWeight.setGeometry(QRect(10, 45, 106, 31))
        self.label_2 = QLabel(self.groupBox_17)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 175, 166, 46))
        self.label_3 = QLabel(self.groupBox_17)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(210, 245, 36, 26))
        self.label_10 = QLabel(self.Resultes)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(930, 630, 121, 16))
        font29 = QFont()
        font29.setPointSize(11)
        self.label_10.setFont(font29)
        self.lbl_uploadreport = QLabel(self.Resultes)
        self.lbl_uploadreport.setObjectName(u"lbl_uploadreport")
        self.lbl_uploadreport.setGeometry(QRect(930, 640, 171, 31))
        self.lbl_uploadreport.setFont(font29)
        self.lbl_uploadreport.setScaledContents(True)
        self.lbl_uploadreport.setWordWrap(True)
        self.tabWidget.addTab(self.Resultes, "")
        self.customer_StaffDB = QWidget()
        self.customer_StaffDB.setObjectName(u"customer_StaffDB")
        self.label_23 = QLabel(self.customer_StaffDB)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(340, 55, 131, 31))
        self.label_23.setFont(font20)
        self.label_23.setStyleSheet(u"")
        self.groupBox_4 = QGroupBox(self.customer_StaffDB)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 10, 316, 401))
        font30 = QFont()
        font30.setFamilies([u"DB Adman X"])
        font30.setPointSize(15)
        font30.setBold(True)
        font30.setItalic(False)
        self.groupBox_4.setFont(font30)
        self.groupBox_4.setStyleSheet(u"")
        self.txt_address_customer_DB = QLineEdit(self.groupBox_4)
        self.txt_address_customer_DB.setObjectName(u"txt_address_customer_DB")
        self.txt_address_customer_DB.setGeometry(QRect(95, 154, 211, 31))
        self.label_20 = QLabel(self.groupBox_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 159, 45, 26))
        self.label_20.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_12 = QLabel(self.groupBox_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 122, 79, 26))
        self.label_12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_21 = QLabel(self.groupBox_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 269, 54, 26))
        self.label_21.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.txt_name_customer_DB = QLineEdit(self.groupBox_4)
        self.txt_name_customer_DB.setObjectName(u"txt_name_customer_DB")
        self.txt_name_customer_DB.setGeometry(QRect(95, 117, 211, 32))
        self.txt_phone_customer_DB = QLineEdit(self.groupBox_4)
        self.txt_phone_customer_DB.setObjectName(u"txt_phone_customer_DB")
        self.txt_phone_customer_DB.setGeometry(QRect(95, 264, 211, 31))
        self.txt_group_customer_DB = QLineEdit(self.groupBox_4)
        self.txt_group_customer_DB.setObjectName(u"txt_group_customer_DB")
        self.txt_group_customer_DB.setGeometry(QRect(95, 190, 211, 32))
        self.label_22 = QLabel(self.groupBox_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 232, 74, 26))
        self.label_22.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_19 = QLabel(self.groupBox_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 195, 47, 26))
        self.label_19.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_42 = QLabel(self.groupBox_4)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 85, 63, 26))
        self.label_42.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.txt_customerID_DB = QLineEdit(self.groupBox_4)
        self.txt_customerID_DB.setObjectName(u"txt_customerID_DB")
        self.txt_customerID_DB.setGeometry(QRect(95, 80, 211, 32))
        self.btn_clear_customer = QPushButton(self.groupBox_4)
        self.btn_clear_customer.setObjectName(u"btn_clear_customer")
        self.btn_clear_customer.setGeometry(QRect(215, 310, 86, 32))
        self.btn_clear_customer.setStyleSheet(u"")
        self.cmb_leaderName_customer_DB = QComboBox(self.groupBox_4)
        self.cmb_leaderName_customer_DB.setObjectName(u"cmb_leaderName_customer_DB")
        self.cmb_leaderName_customer_DB.setGeometry(QRect(95, 227, 211, 32))
        self.splitter_3 = QSplitter(self.groupBox_4)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(65, 350, 236, 34))
        self.splitter_3.setOrientation(Qt.Horizontal)
        self.btn_add_customer = QPushButton(self.splitter_3)
        self.btn_add_customer.setObjectName(u"btn_add_customer")
        self.btn_add_customer.setStyleSheet(u"")
        self.splitter_3.addWidget(self.btn_add_customer)
        self.btn_edit_customer = QPushButton(self.splitter_3)
        self.btn_edit_customer.setObjectName(u"btn_edit_customer")
        self.btn_edit_customer.setStyleSheet(u"")
        self.splitter_3.addWidget(self.btn_edit_customer)
        self.btn_delete_customer = QPushButton(self.splitter_3)
        self.btn_delete_customer.setObjectName(u"btn_delete_customer")
        self.btn_delete_customer.setStyleSheet(u"")
        self.splitter_3.addWidget(self.btn_delete_customer)
        self.tb_customerDetail = QTableWidget(self.customer_StaffDB)
        self.tb_customerDetail.setObjectName(u"tb_customerDetail")
        self.tb_customerDetail.setGeometry(QRect(331, 88, 936, 581))
        self.label_90 = QLabel(self.customer_StaffDB)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setGeometry(QRect(855, 5, 416, 41))
        self.label_90.setFont(font26)
        self.label_90.setStyleSheet(u"color: rgb(252, 62, 39);\n"
"")
        self.label_90.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_99 = QLabel(self.customer_StaffDB)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setGeometry(QRect(860, 50, 381, 16))
        self.label_99.setFont(font27)
        self.label_99.setStyleSheet(u"color: rgb(240, 162, 101);\n"
"")
        self.label_99.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.tabWidget.addTab(self.customer_StaffDB, "")
        self.setting = QWidget()
        self.setting.setObjectName(u"setting")
        self.groupBox_12 = QGroupBox(self.setting)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(10, 10, 206, 316))
        self.groupBox_12.setFont(font2)
        self.btn_SaveWeightOfGradeConfig = QPushButton(self.groupBox_12)
        self.btn_SaveWeightOfGradeConfig.setObjectName(u"btn_SaveWeightOfGradeConfig")
        self.btn_SaveWeightOfGradeConfig.setGeometry(QRect(105, 270, 61, 32))
        self.label_83 = QLabel(self.groupBox_12)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(95, 30, 86, 26))
        font31 = QFont()
        font31.setBold(False)
        self.label_83.setFont(font31)
        self.label_83.setStyleSheet(u"")
        self.label_83.setAlignment(Qt.AlignCenter)
        self.label_82 = QLabel(self.groupBox_12)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(0, 30, 96, 21))
        self.label_82.setStyleSheet(u"")
        self.label_82.setAlignment(Qt.AlignCenter)
        self.btn_Grade_A_3 = QPushButton(self.groupBox_12)
        self.btn_Grade_A_3.setObjectName(u"btn_Grade_A_3")
        self.btn_Grade_A_3.setGeometry(QRect(20, 60, 61, 28))
        font32 = QFont()
        font32.setFamilies([u"DB Adman X"])
        font32.setPointSize(14)
        font32.setBold(True)
        self.btn_Grade_A_3.setFont(font32)
        self.btn_Grade_A_3.setStyleSheet(u"background-color: rgb(16, 128, 64);")
        self.btn_Grade_D_3 = QPushButton(self.groupBox_12)
        self.btn_Grade_D_3.setObjectName(u"btn_Grade_D_3")
        self.btn_Grade_D_3.setGeometry(QRect(20, 164, 61, 28))
        self.btn_Grade_D_3.setFont(font32)
        self.btn_Grade_D_3.setStyleSheet(u"background-color: rgb(253, 128, 8);")
        self.btn_Grade_E_3 = QPushButton(self.groupBox_12)
        self.btn_Grade_E_3.setObjectName(u"btn_Grade_E_3")
        self.btn_Grade_E_3.setGeometry(QRect(20, 199, 61, 27))
        self.btn_Grade_E_3.setFont(font32)
        self.btn_Grade_E_3.setStyleSheet(u"background-color: rgb(252, 2, 128);")
        self.btn_Grade_F_3 = QPushButton(self.groupBox_12)
        self.btn_Grade_F_3.setObjectName(u"btn_Grade_F_3")
        self.btn_Grade_F_3.setGeometry(QRect(20, 233, 61, 28))
        self.btn_Grade_F_3.setFont(font32)
        self.btn_Grade_F_3.setStyleSheet(u"background-color: rgb(252, 1, 7);")
        self.btn_Grade_C_3 = QPushButton(self.groupBox_12)
        self.btn_Grade_C_3.setObjectName(u"btn_Grade_C_3")
        self.btn_Grade_C_3.setGeometry(QRect(20, 129, 61, 28))
        self.btn_Grade_C_3.setFont(font32)
        self.btn_Grade_C_3.setStyleSheet(u"background-color: rgb(255, 255, 10);")
        self.btn_Grade_B_3 = QPushButton(self.groupBox_12)
        self.btn_Grade_B_3.setObjectName(u"btn_Grade_B_3")
        self.btn_Grade_B_3.setGeometry(QRect(20, 95, 61, 27))
        self.btn_Grade_B_3.setFont(font32)
        self.btn_Grade_B_3.setStyleSheet(u"background-color: rgb(128, 255, 7);")
        self.txt_config_Grade_A = QLineEdit(self.groupBox_12)
        self.txt_config_Grade_A.setObjectName(u"txt_config_Grade_A")
        self.txt_config_Grade_A.setGeometry(QRect(105, 60, 61, 28))
        self.txt_config_Grade_A.setAlignment(Qt.AlignCenter)
        self.txt_config_Grade_B = QLineEdit(self.groupBox_12)
        self.txt_config_Grade_B.setObjectName(u"txt_config_Grade_B")
        self.txt_config_Grade_B.setGeometry(QRect(105, 95, 61, 27))
        self.txt_config_Grade_B.setAlignment(Qt.AlignCenter)
        self.txt_config_Grade_C = QLineEdit(self.groupBox_12)
        self.txt_config_Grade_C.setObjectName(u"txt_config_Grade_C")
        self.txt_config_Grade_C.setGeometry(QRect(105, 129, 61, 28))
        self.txt_config_Grade_C.setAlignment(Qt.AlignCenter)
        self.txt_config_Grade_D = QLineEdit(self.groupBox_12)
        self.txt_config_Grade_D.setObjectName(u"txt_config_Grade_D")
        self.txt_config_Grade_D.setGeometry(QRect(105, 164, 61, 28))
        self.txt_config_Grade_D.setAlignment(Qt.AlignCenter)
        self.txt_config_Grade_E = QLineEdit(self.groupBox_12)
        self.txt_config_Grade_E.setObjectName(u"txt_config_Grade_E")
        self.txt_config_Grade_E.setGeometry(QRect(105, 199, 61, 27))
        self.txt_config_Grade_E.setAlignment(Qt.AlignCenter)
        self.txt_config_Grade_F = QLineEdit(self.groupBox_12)
        self.txt_config_Grade_F.setObjectName(u"txt_config_Grade_F")
        self.txt_config_Grade_F.setGeometry(QRect(105, 233, 61, 28))
        self.txt_config_Grade_F.setAlignment(Qt.AlignCenter)
        self.groupBox_13 = QGroupBox(self.setting)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(225, 10, 181, 111))
        self.groupBox_13.setFont(font2)
        self.btn_Save_ConfigWeigthBasket = QPushButton(self.groupBox_13)
        self.btn_Save_ConfigWeigthBasket.setObjectName(u"btn_Save_ConfigWeigthBasket")
        self.btn_Save_ConfigWeigthBasket.setGeometry(QRect(10, 65, 101, 32))
        self.label_84 = QLabel(self.groupBox_13)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(120, 40, 51, 16))
        self.txt_ConfigWeigthBasket = QLineEdit(self.groupBox_13)
        self.txt_ConfigWeigthBasket.setObjectName(u"txt_ConfigWeigthBasket")
        self.txt_ConfigWeigthBasket.setGeometry(QRect(10, 30, 101, 31))
        self.txt_ConfigWeigthBasket.setAlignment(Qt.AlignCenter)
        self.groupBox_15 = QGroupBox(self.setting)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(225, 120, 216, 176))
        self.groupBox_15.setFont(font2)
        self.btn_SavePriceMaterial = QPushButton(self.groupBox_15)
        self.btn_SavePriceMaterial.setObjectName(u"btn_SavePriceMaterial")
        self.btn_SavePriceMaterial.setGeometry(QRect(75, 135, 86, 32))
        self.label_85 = QLabel(self.groupBox_15)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(170, 70, 41, 16))
        font33 = QFont()
        font33.setPointSize(10)
        font33.setBold(False)
        self.label_85.setFont(font33)
        self.label_86 = QLabel(self.groupBox_15)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(10, 35, 61, 21))
        self.label_86.setStyleSheet(u"")
        self.label_87 = QLabel(self.groupBox_15)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(10, 70, 51, 16))
        self.label_88 = QLabel(self.groupBox_15)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setGeometry(QRect(170, 110, 41, 16))
        self.label_88.setFont(font33)
        self.label_89 = QLabel(self.groupBox_15)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setGeometry(QRect(10, 110, 61, 16))
        self.txt_Price_material_BURIRAM = QLineEdit(self.groupBox_15)
        self.txt_Price_material_BURIRAM.setObjectName(u"txt_Price_material_BURIRAM")
        self.txt_Price_material_BURIRAM.setGeometry(QRect(75, 60, 86, 31))
        self.txt_Price_material_BURIRAM.setAlignment(Qt.AlignCenter)
        self.txt_Price_material_SAKON = QLineEdit(self.groupBox_15)
        self.txt_Price_material_SAKON.setObjectName(u"txt_Price_material_SAKON")
        self.txt_Price_material_SAKON.setGeometry(QRect(75, 100, 86, 31))
        self.txt_Price_material_SAKON.setAlignment(Qt.AlignCenter)
        self.groupBox_19 = QGroupBox(self.setting)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.groupBox_19.setGeometry(QRect(445, 15, 281, 281))
        self.groupBox_19.setFont(font2)
        self.txt_password_staff_config = QLineEdit(self.groupBox_19)
        self.txt_password_staff_config.setObjectName(u"txt_password_staff_config")
        self.txt_password_staff_config.setGeometry(QRect(90, 104, 181, 33))
        self.label_26 = QLabel(self.groupBox_19)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 70, 65, 25))
        self.label_25 = QLabel(self.groupBox_19)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 110, 66, 25))
        self.txt_username_staff_config = QLineEdit(self.groupBox_19)
        self.txt_username_staff_config.setObjectName(u"txt_username_staff_config")
        self.txt_username_staff_config.setGeometry(QRect(90, 67, 181, 32))
        self.label_27 = QLabel(self.groupBox_19)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(20, 150, 81, 25))
        self.label_98 = QLabel(self.groupBox_19)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setGeometry(QRect(35, 35, 43, 25))
        self.label_98.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.txt_staff_id_config = QLineEdit(self.groupBox_19)
        self.txt_staff_id_config.setObjectName(u"txt_staff_id_config")
        self.txt_staff_id_config.setGeometry(QRect(90, 30, 181, 32))
        self.txt_name_staff_config = QLineEdit(self.groupBox_19)
        self.txt_name_staff_config.setObjectName(u"txt_name_staff_config")
        self.txt_name_staff_config.setGeometry(QRect(90, 185, 181, 32))
        self.label_41 = QLabel(self.groupBox_19)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 190, 70, 25))
        self.btn_clear_staff_config = QPushButton(self.groupBox_19)
        self.btn_clear_staff_config.setObjectName(u"btn_clear_staff_config")
        self.btn_clear_staff_config.setGeometry(QRect(190, 235, 81, 32))
        self.btn_clear_staff_config.setStyleSheet(u"")
        self.cmb_level_staff_config = QComboBox(self.groupBox_19)
        self.cmb_level_staff_config.setObjectName(u"cmb_level_staff_config")
        self.cmb_level_staff_config.setGeometry(QRect(110, 145, 156, 31))
        self.btn_add_staff = QPushButton(self.groupBox_19)
        self.btn_add_staff.setObjectName(u"btn_add_staff")
        self.btn_add_staff.setGeometry(QRect(20, 235, 51, 32))
        self.btn_add_staff.setStyleSheet(u"")
        self.btn_edit_staff = QPushButton(self.groupBox_19)
        self.btn_edit_staff.setObjectName(u"btn_edit_staff")
        self.btn_edit_staff.setGeometry(QRect(75, 235, 56, 32))
        self.btn_edit_staff.setStyleSheet(u"")
        self.btn_delete_staff = QPushButton(self.groupBox_19)
        self.btn_delete_staff.setObjectName(u"btn_delete_staff")
        self.btn_delete_staff.setGeometry(QRect(135, 235, 51, 32))
        self.btn_delete_staff.setStyleSheet(u"")
        self.groupBox_3 = QGroupBox(self.setting)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(730, 65, 536, 611))
        self.groupBox_3.setFont(font2)
        self.tb_staffDetail = QTableWidget(self.groupBox_3)
        self.tb_staffDetail.setObjectName(u"tb_staffDetail")
        self.tb_staffDetail.setGeometry(QRect(10, 25, 521, 571))
        self.groupBox_18 = QGroupBox(self.setting)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(10, 335, 206, 91))
        self.groupBox_18.setFont(font2)
        self.txt_SerialPortName = QLineEdit(self.groupBox_18)
        self.txt_SerialPortName.setObjectName(u"txt_SerialPortName")
        self.txt_SerialPortName.setGeometry(QRect(10, 45, 116, 31))
        self.label_13 = QLabel(self.groupBox_18)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 25, 141, 16))
        self.btn_SerialPortSet = QPushButton(self.groupBox_18)
        self.btn_SerialPortSet.setObjectName(u"btn_SerialPortSet")
        self.btn_SerialPortSet.setGeometry(QRect(135, 45, 66, 32))
        self.btn_SerialPortSet.setStyleSheet(u"")
        self.label_100 = QLabel(self.setting)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setGeometry(QRect(855, 5, 416, 41))
        self.label_100.setFont(font26)
        self.label_100.setStyleSheet(u"color: rgb(252, 62, 39);\n"
"")
        self.label_100.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_101 = QLabel(self.setting)
        self.label_101.setObjectName(u"label_101")
        self.label_101.setGeometry(QRect(860, 50, 381, 16))
        self.label_101.setFont(font27)
        self.label_101.setStyleSheet(u"color: rgb(240, 162, 101);\n"
"")
        self.label_101.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.tabWidget.addTab(self.setting, "")
        self.database = QWidget()
        self.database.setObjectName(u"database")
        self.label_103 = QLabel(self.database)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setGeometry(QRect(855, 5, 416, 41))
        self.label_103.setFont(font26)
        self.label_103.setStyleSheet(u"color: rgb(252, 62, 39);\n"
"")
        self.label_103.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_105 = QLabel(self.database)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setGeometry(QRect(860, 50, 381, 16))
        self.label_105.setFont(font27)
        self.label_105.setStyleSheet(u"color: rgb(240, 162, 101);\n"
"")
        self.label_105.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.tb_ALL_DataList = QTableWidget(self.database)
        self.tb_ALL_DataList.setObjectName(u"tb_ALL_DataList")
        self.tb_ALL_DataList.setGeometry(QRect(5, 10, 146, 661))
        self.btn_SaveExcelFile = QPushButton(self.database)
        self.btn_SaveExcelFile.setObjectName(u"btn_SaveExcelFile")
        self.btn_SaveExcelFile.setGeometry(QRect(320, 630, 141, 36))
        self.btn_SaveExcelFile.setFont(font3)
        self.btn_SaveExcelFile.setStyleSheet(u"background-color: rgb(70, 212, 104);")
        self.tb_OrderDetail = QTableWidget(self.database)
        self.tb_OrderDetail.setObjectName(u"tb_OrderDetail")
        self.tb_OrderDetail.setGeometry(QRect(155, 35, 311, 596))
        self.tb_ALL_DataRecoreList = QTableWidget(self.database)
        self.tb_ALL_DataRecoreList.setObjectName(u"tb_ALL_DataRecoreList")
        self.tb_ALL_DataRecoreList.setGeometry(QRect(470, 80, 801, 591))
        self.label_43 = QLabel(self.database)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(510, 50, 186, 31))
        self.label_43.setFont(font23)
        self.label_43.setStyleSheet(u"")
        self.label_46 = QLabel(self.database)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(155, 5, 211, 31))
        self.label_46.setFont(font23)
        self.label_46.setStyleSheet(u"")
        self.tabWidget.addTab(self.database, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e1c\u0e39\u0e49\u0e02\u0e32\u0e22", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d\u0e01\u0e25\u0e38\u0e48\u0e21/\u0e2b\u0e21\u0e39\u0e48\u0e1a\u0e49\u0e32\u0e19", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u0e2b\u0e31\u0e27\u0e2b\u0e19\u0e49\u0e32\u0e01\u0e25\u0e38\u0e48\u0e21", None))
        self.lbl_customer_name.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_customer_Group.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_customer_LeadGroupName.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e2b\u0e31\u0e2a", None))
        self.lbl_customer_ID.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_customer_Address.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u0e08\u0e31\u0e07\u0e2b\u0e27\u0e31\u0e14", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e1a\u0e2d\u0e23\u0e4c\u0e42\u0e17\u0e23\u0e28\u0e31\u0e1e\u0e17\u0e4c", None))
        self.lbl_customer_phone.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.btn_customerSelect.setText(QCoreApplication.translate("MainWindow", u"\u0e04\u0e49\u0e19\u0e2b\u0e32", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e2b\u0e31\u0e2a\u0e1c\u0e39\u0e49\u0e02\u0e32\u0e22", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\u0e40\u0e25\u0e02\u0e17\u0e35\u0e48\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48", None))
        self.lbl_OrderID.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_Order_Date.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e25\u0e02\u0e17\u0e35\u0e48", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e27\u0e25\u0e32", None))
        self.lbl_Order_Time.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.btn_orderSet.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"\u0e0a\u0e19\u0e34\u0e14\u0e1e\u0e31\u0e19\u0e18\u0e38\u0e4c\u0e43\u0e1a\u0e2b\u0e21\u0e48\u0e2d\u0e19", None))
        self.cmb_MaterialType.setCurrentText("")
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"\u0e23\u0e32\u0e22\u0e25\u0e30\u0e40\u0e2d\u0e35\u0e22\u0e14\u0e43\u0e1a\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d\u0e43\u0e1a\u0e2b\u0e21\u0e48\u0e2d\u0e19", None))
        self.lbl_Clock.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01 (kg.)", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"\u0e40\u0e01\u0e23\u0e14\u0e27\u0e31\u0e15\u0e16\u0e38\u0e14\u0e34\u0e1a", None))
        self.btn_Grade_F.setText(QCoreApplication.translate("MainWindow", u"F", None))
        self.btn_Grade_B.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.btn_Grade_C.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.btn_Grade_D.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.btn_Grade_A.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.btn_Grade_E.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.btn_Save_Main.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
#if QT_CONFIG(shortcut)
        self.btn_Save_Main.setShortcut(QCoreApplication.translate("MainWindow", u"Enter", None))
#endif // QT_CONFIG(shortcut)
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e1a\u0e2d\u0e23\u0e4c\u0e15\u0e23\u0e30\u0e01\u0e23\u0e49\u0e32", None))
        self.lbl_MaterialGrade_main.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.btn_DeleteData_main.setText(QCoreApplication.translate("MainWindow", u"\u0e25\u0e1a\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25", None))
        self.cmb_container.setCurrentText("")
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"\u0e0a\u0e19\u0e34\u0e14\u0e20\u0e32\u0e0a\u0e19\u0e30", None))
        self.btn_ClearWeight.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e04\u0e25\u0e35\u0e22\u0e23\u0e4c", None))
        self.lbl_dateNow.setText(QCoreApplication.translate("MainWindow", u"00-00-0000", None))
        self.lbl_weight.setText(QCoreApplication.translate("MainWindow", u"00.00", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e01\u0e32\u0e23\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.groupBox_22.setTitle(QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e25\u0e02\u0e17\u0e35\u0e48", None))
        self.lbl_customer_NameLeadGroup_main.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u0e0a\u0e19\u0e34\u0e14\u0e1e\u0e31\u0e19\u0e18\u0e38\u0e4c", None))
        self.lbl_Order_Date_main.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_customer_name_main.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_Order_Time_main.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_building_main.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_OrderID_main.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"\u0e1c\u0e39\u0e49\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"\u0e2b\u0e31\u0e27\u0e2b\u0e19\u0e49\u0e32\u0e01\u0e25\u0e38\u0e48\u0e21", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e27\u0e25\u0e32", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"\u0e1c\u0e39\u0e49\u0e02\u0e32\u0e22", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48", None))
        self.lbl_Staff_name_main.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"\u0e2d\u0e32\u0e04\u0e32\u0e23", None))
        self.lbl_MaterialType_main.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.btn_RandomWeight.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e38\u0e48\u0e21\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01", None))
        self.btn_Create_Order.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e23\u0e49\u0e32\u0e07\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"\u0e2d\u0e32\u0e04\u0e32\u0e23\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.cmd_building.setCurrentText("")
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e2a\u0e34\u0e48\u0e07\u0e40\u0e08\u0e37\u0e2d\u0e1b\u0e19(\u0e23\u0e27\u0e21)", None))
        self.btn_SaveWasteWeight.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.txt_wasteWeight.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.groupBox_21.setTitle(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e16\u0e38\u0e07\u0e1a\u0e23\u0e23\u0e08\u0e38(\u0e23\u0e27\u0e21)", None))
        self.btn_SaveContainerWeight.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.txt_ContainerWeight.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e1c\u0e39\u0e49\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d", None))
        self.lbl_Staff_name.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e2b\u0e31\u0e2a", None))
        self.lbl_Staff_ID.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_UserLevelShow.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"THAI SILK PRODUCTS COMPANY LIMITED", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e44\u0e17\u0e22\u0e0b\u0e34\u0e25\u0e04\u0e4c\u0e42\u0e1b\u0e23\u0e14\u0e31\u0e04\u0e2a\u0e4c \u0e08\u0e33\u0e01\u0e31\u0e14", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e01\u0e32\u0e23\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"\u0e23\u0e32\u0e22\u0e25\u0e30\u0e40\u0e2d\u0e35\u0e22\u0e14\u0e43\u0e1a\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e25\u0e02\u0e17\u0e35\u0e48\u0e43\u0e1a\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.btn_CreateResulte.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e23\u0e49\u0e32\u0e07\u0e23\u0e32\u0e22\u0e07\u0e32\u0e19\u0e2a\u0e23\u0e38\u0e1b\u0e1c\u0e25", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e01\u0e32\u0e23\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48", None))
        self.lbl_OrderID_3.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_Order_Date_3.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e25\u0e02\u0e17\u0e35\u0e48", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e27\u0e25\u0e32", None))
        self.lbl_Order_Time_3.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u0e1c\u0e39\u0e49\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"\u0e1c\u0e39\u0e49\u0e02\u0e32\u0e22", None))
        self.lbl_Staff_name_3.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_Staff_ID_2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e2b\u0e31\u0e2a", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e2b\u0e31\u0e2a", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"\u0e2b\u0e31\u0e27\u0e2b\u0e19\u0e49\u0e32\u0e01\u0e25\u0e38\u0e48\u0e21", None))
        self.lbl_customer_HeadGroup_2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_customer_ID_2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_building_2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"\u0e2d\u0e32\u0e04\u0e32\u0e23", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"\u0e0a\u0e19\u0e34\u0e14\u0e1e\u0e31\u0e19\u0e18\u0e38\u0e4c", None))
        self.lbl_MaterialType_2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.groupBox_16.setTitle(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e43\u0e1a\u0e2b\u0e21\u0e48\u0e2d\u0e19", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01(\u0e23\u0e27\u0e21)", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"(\u0e2b\u0e31\u0e01) \u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e43\u0e1a\u0e40\u0e2a\u0e35\u0e22\u0e23\u0e27\u0e21 (kg)", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"(\u0e2b\u0e31\u0e01) \u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e15\u0e30\u0e01\u0e23\u0e49\u0e32\u0e23\u0e27\u0e21 (kg)", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e43\u0e1a\u0e2b\u0e21\u0e48\u0e2d\u0e19\u0e2a\u0e38\u0e17\u0e18\u0e34", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"\u0e08\u0e33\u0e19\u0e27\u0e19\u0e15\u0e30\u0e01\u0e23\u0e49\u0e32", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e15\u0e30\u0e01\u0e23\u0e49\u0e32", None))
        self.label_70.setText(QCoreApplication.translate("MainWindow", u"\u0e43\u0e1a", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"kg/\u0e43\u0e1a", None))
        self.lbl_Resulte_TotalBasket.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lbl_Resulte_weightBasket.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lbl_Resulte_TotalWeightMeterial.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lbl_Resulte_TotalWeightReject.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lbl_Resulte_TotalWeightBasket.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lbl_Resulte_TotalWeight_toManuFactory.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lbl_Resulte_ContainerWeight.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_104.setText(QCoreApplication.translate("MainWindow", u"(\u0e2b\u0e31\u0e01) \u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e16\u0e38\u0e07\u0e23\u0e27\u0e21 (kg)", None))
        self.label_102.setText(QCoreApplication.translate("MainWindow", u"(\u0e2b\u0e31\u0e01) \u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e2a\u0e34\u0e48\u0e07\u0e40\u0e08\u0e37\u0e2d\u0e1b\u0e19\u0e23\u0e27\u0e21 (kg)", None))
        self.lbl_Resulte_TotalWeightReject_west.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e32\u0e22\u0e25\u0e30\u0e40\u0e2d\u0e35\u0e22\u0e14\u0e01\u0e32\u0e23\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d\u0e43\u0e1a\u0e2b\u0e21\u0e48\u0e2d\u0e19", None))
        self.groupBox_20.setTitle(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e23\u0e38\u0e1b\u0e22\u0e2d\u0e14\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.label_91.setText(QCoreApplication.translate("MainWindow", u"(\u0e2a\u0e48\u0e07\u0e1d\u0e48\u0e32\u0e22\u0e01\u0e32\u0e23\u0e40\u0e07\u0e34\u0e19)", None))
        self.label_92.setText(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e43\u0e1a\u0e2b\u0e21\u0e48\u0e2d\u0e19\u0e2a\u0e38\u0e17\u0e18\u0e34", None))
        self.label_93.setText(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01", None))
        self.lbl_Resulte_TotalWeight_Accounting.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_96.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e32\u0e04\u0e32\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d (\u0e1a\u0e32\u0e17/\u0e01\u0e01.)", None))
        self.label_95.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e32\u0e22\u0e1e\u0e31\u0e19\u0e18\u0e38\u0e4c", None))
        self.lbl_Resulte_Type.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_Resulte_Price.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_94.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e27\u0e21\u0e40\u0e1b\u0e47\u0e19\u0e40\u0e07\u0e34\u0e19\u0e2a\u0e38\u0e17\u0e18\u0e34", None))
        self.lbl_Resulte_TotalPrice.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_97.setText(QCoreApplication.translate("MainWindow", u"(\u0e1a\u0e32\u0e17)", None))
        self.btn_UploadReport.setText(QCoreApplication.translate("MainWindow", u"\u0e2d\u0e31\u0e1e\u0e42\u0e2b\u0e25\u0e14\u0e23\u0e32\u0e22\u0e07\u0e32\u0e19", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e44\u0e17\u0e22\u0e0b\u0e34\u0e25\u0e04\u0e4c\u0e42\u0e1b\u0e23\u0e14\u0e31\u0e04\u0e2a\u0e4c \u0e08\u0e33\u0e01\u0e31\u0e14", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"THAI SILK PRODUCTS COMPANY LIMITED", None))
        self.groupBox_17.setTitle(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e43\u0e1a\u0e2b\u0e21\u0e48\u0e2d\u0e19\u0e2b\u0e19\u0e49\u0e32\u0e44\u0e23\u0e48", None))
        self.lbl_Resulte_ExternalWeight.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_72.setText(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e23\u0e27\u0e21", None))
        self.btn_SaveExternalWeight.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.checkBox_ExteranalWeight.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u0e08\u0e32\u0e01\u0e41\u0e2b\u0e25\u0e48\u0e07\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d\u0e2b\u0e19\u0e49\u0e32\u0e44\u0e23\u0e48", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"(kg)", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u0e2d\u0e31\u0e1b\u0e42\u0e2b\u0e25\u0e14\u0e23\u0e32\u0e22\u0e07\u0e32\u0e19", None))
        self.lbl_uploadreport.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Resultes), QCoreApplication.translate("MainWindow", u"\u0e2a\u0e23\u0e38\u0e1b", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e23\u0e32\u0e22\u0e0a\u0e37\u0e48\u0e2d\u0e1c\u0e39\u0e49\u0e02\u0e32\u0e22", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e1c\u0e39\u0e49\u0e02\u0e32\u0e22", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u0e08\u0e31\u0e07\u0e2b\u0e27\u0e31\u0e14", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d-\u0e19\u0e32\u0e21\u0e2a\u0e01\u0e38\u0e25", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u0e42\u0e17\u0e23\u0e28\u0e31\u0e1e\u0e17\u0e4c", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"\u0e2b\u0e31\u0e27\u0e2b\u0e19\u0e49\u0e32\u0e01\u0e25\u0e38\u0e48\u0e21", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u0e2b\u0e21\u0e39\u0e48\u0e1a\u0e49\u0e32\u0e19", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e2b\u0e31\u0e2a\u0e1c\u0e39\u0e49\u0e02\u0e32\u0e22", None))
        self.btn_clear_customer.setText(QCoreApplication.translate("MainWindow", u"\u0e25\u0e49\u0e32\u0e07\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25", None))
        self.btn_add_customer.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e1e\u0e34\u0e48\u0e21", None))
        self.btn_edit_customer.setText(QCoreApplication.translate("MainWindow", u"\u0e41\u0e01\u0e49\u0e44\u0e02", None))
        self.btn_delete_customer.setText(QCoreApplication.translate("MainWindow", u"\u0e25\u0e1a", None))
        self.label_90.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e44\u0e17\u0e22\u0e0b\u0e34\u0e25\u0e04\u0e4c\u0e42\u0e1b\u0e23\u0e14\u0e31\u0e04\u0e2a\u0e4c \u0e08\u0e33\u0e01\u0e31\u0e14", None))
        self.label_99.setText(QCoreApplication.translate("MainWindow", u"THAI SILK PRODUCTS COMPANY LIMITED", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.customer_StaffDB), QCoreApplication.translate("MainWindow", u"\u0e23\u0e32\u0e22\u0e0a\u0e37\u0e48\u0e2d\u0e1c\u0e39\u0e49\u0e02\u0e32\u0e22", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"\u0e04\u0e38\u0e13\u0e20\u0e32\u0e1e\u0e27\u0e31\u0e15\u0e16\u0e38\u0e14\u0e34\u0e1a", None))
        self.btn_SaveWeightOfGradeConfig.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.label_83.setText(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e17\u0e35\u0e48\u0e2b\u0e31\u0e01", None))
        self.label_82.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e01\u0e23\u0e14\u0e27\u0e31\u0e15\u0e16\u0e38\u0e14\u0e34\u0e1a", None))
        self.btn_Grade_A_3.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.btn_Grade_D_3.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.btn_Grade_E_3.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.btn_Grade_F_3.setText(QCoreApplication.translate("MainWindow", u"F", None))
        self.btn_Grade_C_3.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.btn_Grade_B_3.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e15\u0e30\u0e01\u0e23\u0e49\u0e32", None))
        self.btn_Save_ConfigWeigthBasket.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.label_84.setText(QCoreApplication.translate("MainWindow", u"\u0e01\u0e34\u0e42\u0e25\u0e01\u0e23\u0e31\u0e21", None))
        self.groupBox_15.setTitle(QCoreApplication.translate("MainWindow", u"\u0e23\u0e32\u0e04\u0e32\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.btn_SavePriceMaterial.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.label_85.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e32\u0e17/\u0e01\u0e01.", None))
        self.label_86.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e32\u0e22\u0e1e\u0e31\u0e19\u0e18\u0e38\u0e4c", None))
        self.label_87.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e38\u0e23\u0e35\u0e23\u0e31\u0e21\u0e22\u0e4c", None))
        self.label_88.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e32\u0e17/\u0e01\u0e01.", None))
        self.label_89.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e01\u0e25\u0e19\u0e04\u0e23", None))
        self.groupBox_19.setTitle(QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e40\u0e08\u0e49\u0e32\u0e2b\u0e19\u0e49\u0e32\u0e17\u0e35\u0e48\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Username", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e34\u0e17\u0e18\u0e34\u0e1c\u0e39\u0e49\u0e43\u0e0a\u0e49\u0e07\u0e32\u0e19", None))
        self.label_98.setText(QCoreApplication.translate("MainWindow", u"UserID", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d\u0e1e\u0e19\u0e31\u0e01\u0e07\u0e32\u0e19", None))
        self.btn_clear_staff_config.setText(QCoreApplication.translate("MainWindow", u"\u0e25\u0e49\u0e32\u0e07\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25", None))
        self.btn_add_staff.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e1e\u0e34\u0e48\u0e21", None))
        self.btn_edit_staff.setText(QCoreApplication.translate("MainWindow", u"\u0e41\u0e01\u0e49\u0e44\u0e02", None))
        self.btn_delete_staff.setText(QCoreApplication.translate("MainWindow", u"\u0e25\u0e1a", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e40\u0e08\u0e49\u0e32\u0e2b\u0e19\u0e49\u0e32\u0e1c\u0e39\u0e49\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.groupBox_18.setTitle(QCoreApplication.translate("MainWindow", u"\u0e15\u0e31\u0e49\u0e07\u0e04\u0e48\u0e32\u0e40\u0e04\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e0a\u0e31\u0e48\u0e07", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Serial Port ", None))
        self.btn_SerialPortSet.setText(QCoreApplication.translate("MainWindow", u"SET", None))
        self.label_100.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e44\u0e17\u0e22\u0e0b\u0e34\u0e25\u0e04\u0e4c\u0e42\u0e1b\u0e23\u0e14\u0e31\u0e04\u0e2a\u0e4c \u0e08\u0e33\u0e01\u0e31\u0e14", None))
        self.label_101.setText(QCoreApplication.translate("MainWindow", u"THAI SILK PRODUCTS COMPANY LIMITED", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setting), QCoreApplication.translate("MainWindow", u"\u0e15\u0e31\u0e49\u0e07\u0e04\u0e48\u0e32", None))
        self.label_103.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e44\u0e17\u0e22\u0e0b\u0e34\u0e25\u0e04\u0e4c\u0e42\u0e1b\u0e23\u0e14\u0e31\u0e04\u0e2a\u0e4c \u0e08\u0e33\u0e01\u0e31\u0e14", None))
        self.label_105.setText(QCoreApplication.translate("MainWindow", u"THAI SILK PRODUCTS COMPANY LIMITED", None))
        self.btn_SaveExcelFile.setText(QCoreApplication.translate("MainWindow", u"Save Excel File", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e32\u0e22\u0e25\u0e30\u0e40\u0e2d\u0e35\u0e22\u0e14\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e01\u0e32\u0e23\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.database), QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e01\u0e32\u0e23\u0e23\u0e31\u0e1a\u0e0b\u0e37\u0e49\u0e2d", None))
    # retranslateUi

